project_id = "euvmzwkdiixnmyxuwodg"

[functions.analisar-indicador]
verify_jwt = false

[functions.sugerir-metas]
verify_jwt = false

[functions.chat-analista]
verify_jwt = false

[functions.gerar-analise-consultiva]
verify_jwt = false

[functions.criar-usuario]
verify_jwt = false

[functions.analisar-widget]
verify_jwt = false
